### ISSUE TITLE
Cross-compilation with Buildroot and integration with localtunnel

### ISSUE THREAD

**Issue by alexander-sil** [mpromonet/v4l2camera#20]
Hello. I would like to run this web interface on a headless IoT device (Raspberry Pi 3B with Defender webcam) with an OS image built with Buildroot, and expose this web interface to the Internet using localtunnel. Please add an ability to cross-compile this V4L2 web interface project to aarch64 and integrate it into Buildroot. Localtunnel integration is secondary.

**Comment by mpromonet** [comment]
Hi,

I made some tries with openwrt without problem, I guess it should work setting standard variable running cmake.

Best Regards,
Michel.

**Comment by alexander-sil** [comment]
Please give me the aarch64 binaries of v4l2camera, as I am unable to cross-compile the project due to technical reasons. I prefer not to try compiling the packages anymore, I would like you to simply cross-compile v4l2camera to aarch64-linux-gnu for me. Thanks in advance.

**Comment by mpromonet** [comment]
Hi,

You might read https://github.com/mpromonet/v4l2camera/blob/master/.github/CONTRIBUTING.md

Best Regards,
Michel.
