### ISSUE TITLE
v4l2rtsp server on with web

### ISSUE THREAD

**Issue by Ekitji** [mpromonet/v4l2camera#4]
Hi there!

Great work with this! im running your rtspserver and thought that this would give the chance to control brightness and so on for the camera but i cant get it work due to busy resource.

is there a chance to work around this? running the rtsp server and have access to the webinterface "control" functions? without activating the camera streaming on the webpage due to this is causing the problem.

Thanks again for a great work!

**Comment by mpromonet** [comment]
Hi Ekitji,

I made some tries including RTSP server in this project, then the device is openned only by v4l2web and then allow some controls while streaming.
Some works is needed to allow changing resolution or format.

Best Regards,
Michel.

**Comment by mpromonet** [comment]
Hi,

I am closing this issue, as it is now implemented using v4l2rtspserver as a librairy to share the filedescriptor use to control and to capture.

Best Reagards,
Michel.
